apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/backend/color
nameSuffix: "-green"
labels:
  - pairs:
      color: green
    includeSelectors: true
images:
  - name: PLACEHOLDER_ACR_NAME.azurecr.io/eskom-forecast-api
    newName: PLACEHOLDER_ACR_NAME.azurecr.io/eskom-forecast-api
    newTag: PLACEHOLDER_TAG
