apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-coal-stockpile-prod
labels:
  - pairs:
      env: prod
    includeSelectors: true
resources:
  - namespace.yaml
  - ../../../base/frontend/shared
  - blue
  - green
